### ISSUE TITLE
auto_disconnect doesn't seem to work

### ISSUE THREAD

**Issue by leda-ferreira** [voryx/PgAsync#12]
Since yesterday I'm having _"FATAL:  remaining connection slots are reserved for non-replication superuser connections"_ errors. When I started using PgAsync a few weeks ago I raised `max_connections` to 999 and this number was enough until now.

So I tried enabling `auto_disconnect`, despite not having tested this before. Things wouldn't work at all. My expectation was that when `auto_disconnect` is set to `true`, each call to the `query` and `executeStatement` methods would result in a new connection, but `htop` shows a growing list of idle connections. I even tried to use PgBouncer in transaction mode and have the application connect to it instead of the database, but this didn't work too.

I took a look at the source code. New connections are stored for later use regardless of the `auto_disconnect` setting. I think that if we are going to discard the connection after the query completes anyway, we shouldn't even add them to the pool. So I tried this change on `/src/PgAsync/Client.php`, line 68:

```php
        $connection          = new Connection($this->parameters, $this->loop);
        if (!$connection->auto_disconnect) { // I changed this property visibility to public just for testing
            $this->connections[] = $connection;
        }
```
And then things worked, with or without PgBouncer: no more accumulation of idle connections, and the application would work just like before the problem started. So, it appears that in some situations, the test executed at line 61 might result in true even if connection isn't open anymore, causing the application to hang.

Also, when we are not using `auto_disconnect`, the connections previously added to the pool don't appear to ever be reutilized: when the _"remaining connection slots are reserved"_ errors started, there were hundreds of iddle connections. They remain in idle status until Postgres terminates them.

I'm now going to experiment `auto_disconnect` + PgBouncer on production and see how it performs.

**Comment by leda-ferreira** [comment]
I just remembered another thing: when PgAsync disconnects, PgBouncer log shows: `closing because: client unexpected eof`. When PDO or psql disconnect, it shows: `closing because: client close request`. So, it might be that disconnection isn't being properly handled.

**Comment by mbonneau** [comment]
Did not intend to close this issue (happened in merge) as there were other issues with `auto_disconnect` that hopefully will be addressed in #15 .

@leda-ferreira - If you can test that this is disconnecting properly - that would be helpful.

**Comment by leda-ferreira** [comment]
@mbonneau thank you a lot :-) I'll test as soon as possible

**Comment by mbonneau** [comment]
@leda-ferreira - I did find an issue where if there is an error on the connection, it is still not auto-disconnecting. I am writing a test for this now and will make a PR shortly.

**Comment by leda-ferreira** [comment]
@mbonneau it appears to be working now. Thank you very much. BTW, I was wrong when I said idle connections weren't being reused: they were. I was just oppening too much connections at the same time and there was nothing to be reused. Then I would look into htop and the connections were idle again.
