### ISSUE TITLE
Consider wrapping all queries in a transaction

### ISSUE THREAD

**Issue by mbonneau** [voryx/PgAsync#2]
If there is a disconnect that happens, the backend may or may not complete the request. If the non-SELECT query is wrapped in a transaction and there is a disconnect, the transaction will be automatically rolled back.

**Comment by jmealo** [comment]
@mbonneau: https://www.postgresql.org/docs/11/sql-notify.html there are some special considerations for `NOTIFY` usage within a transaction listed in the Notes

**Comment by mbonneau** [comment]
I do see that - right now there are no automatic transactions - you would have to manage them yourself on an individual connection.

Right now, if you are `NOTIFY`ing with `executeStatement` or `query`, if will always grab an idle connection.
