### ISSUE TITLE
Query without prepared statement

### ISSUE THREAD

**Issue by Tatikoma** [voryx/PgAsync#21]
I need interface to query database without prepared statement. Just simple query.

I need it because pgbouncer in transaction pooling mode doesnt support prepared statements.

Is there any way to query postgres without prepared statement using this library?

**Comment by Tatikoma** [comment]
I talking about something like PDO::ATTR_EMULATE_PREPARES option.

**Comment by mbonneau** [comment]
Client::query does not use prepared statements, it just passes the query text as-is.

**Comment by Tatikoma** [comment]
It seems I was looking wrong way. Thank you.
