### ISSUE TITLE
PgAsync with PipelineDB

### ISSUE THREAD

**Issue by shestero** [voryx/PgAsync#31]
Is it possible to use PgAsync for reading the PipelineDB continuous streams?

**Comment by mbonneau** [comment]
@shestero - Just reading over the docs real quick: Is there anywhere that they mention the ability to read to a continuous stream?

**Comment by shestero** [comment]
Google find nowhere words "PgAsync" and "PipelineDB" together.
That I really need is non-blocking reading of continuous stream in PHP (also in Java, C++).

**Comment by mbonneau** [comment]
You had asked if it was possible to read continuous streams from @pipelinedb. The answer to that is: I don't know if it is possible to read continuous streams, so I was not able to test that.

PgAsync can be used with PipelineDB (I have tested reading continuous views). If you experience any problems, feel free to open an issue.

**Comment by shestero** [comment]
thank you!
