### ISSUE TITLE
Listening for Notifications

### ISSUE THREAD

**Issue by mpjraaij** [voryx/PgAsync#33]
Hi,

Is there a good way to listen to triggers using your library?

Thanks,
Maarten

**Comment by mbonneau** [comment]
I am not sure what you mean by listening to triggers? Are you referring to the LISTEN command?

**Comment by mpjraaij** [comment]
Sorry I did not get a notification of your reply. Yes, I am referring to the LISTEN command :)

**Comment by mbonneau** [comment]
This is not currently supported. It does not seem like it would be difficult to implement. The best way to do it would just be to reserve a connection for listening and not run any queries on it. Maybe add a `->listen([...array of things to listen to...])` and it would emit events as the were produced.

I don't think I have the time to implement this at the moment, but if someone else wants to take a look at it, that would be great.

**Comment by mpjraaij** [comment]
I noticed you implemented it! Thank you so much, sorry for the late comment. I did not revisit the repo until now and somehow did not receive notifications from here. Looks awesome :)
