### ISSUE TITLE
Observer not set error when executing and connection fails

### ISSUE THREAD

**Issue by mbonneau** [voryx/PgAsync#35]
When using `executeStatement` on a `Client`, if the connection fails (auth error in my case), the cryptic error below is produced:

```Fatal error: Uncaught Exception: Observer not set on command.```

**Comment by soulilya** [comment]
You must debug error yourself. This error because of database error. Dig deeper)

**Comment by mbonneau** [comment]
I have not encountered this in some time - closing issue
