### ISSUE TITLE
Postgres dockerized [Suggestion]

### ISSUE THREAD

**Issue by raphaeldealmeida** [voryx/PgAsync#37]
Hi guys,
I want to contribute, but I think it is too hard to run the tests, because it is necessary to configure Postgres.
I suggest using postgres in a docker container to resolve this problem and lower initial barrier for new contributors

This is a official image https://hub.docker.com/_/postgres

**Comment by mbonneau** [comment]
@raphaeldealmeida This sounds like it could be a good idea. I don't have the time to get this put together right now. If someone would like to give this a shot, that would be great.
