### ISSUE TITLE
Unable to query database in example folder

### ISSUE THREAD

**Issue by shemgp** [voryx/PgAsync#5]
Hello,

I'm testing if this library will work in an Ubuntu machine, and it doesn't seem to be able to get data from the database.  I go to vendor/voryx/pgasync/example/ and edit Prepare.php to add password and change the database and username to connect to my local PostgreSQL instance.  Then I run php Prepare.php and there is not output. It just hangs. I also try other files like SequentialQueries.php and it hangs too.  When I try SimpleQuery.php, it displays:

php SimpleQuery.php 
Connection State: 1
Connection State: 1
There are 2 connections. (0)
Connection State: 1
Connection State: 1
There are 2 connections. (1)
^C

Hope this helps in diagnosing this problem.  Thank you for your help.

**Comment by mbonneau** [comment]
I have not added the ability to log in with passwords yet as I have been testing with a trusted connection. I am working to add that now.

**Comment by mbonneau** [comment]
Hi @shemgp ,

I have added password authentication (cleartext). Please let me know if this addresses the issue.

**Comment by mbonneau** [comment]
I have also added MD5 authentication in the latest commit.
